using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SebastianGuzmanMorla.DDD.Generator;

[Generator]
public sealed class EntityTypeConfigurationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol?> configurations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (ctx, _) =>
                {
                    ClassDeclarationSyntax classDeclaration = (ClassDeclarationSyntax)ctx.Node;

                    if (ctx.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol symbol)
                    {
                        return null;
                    }

                    if (symbol.IsAbstract)
                    {
                        return null;
                    }

                    foreach (INamedTypeSymbol? iface in symbol.AllInterfaces)
                        if (iface.Name == "IEntityTypeConfiguration" &&
                            iface.ContainingNamespace.ToDisplayString() == "Microsoft.EntityFrameworkCore")
                        {
                            return symbol;
                        }

                    return null;
                })
            .Where(static s => s is not null)!;

        IncrementalValueProvider<(Compilation Left, ImmutableArray<INamedTypeSymbol?> Right)> compilationAndConfigs =
            context.CompilationProvider.Combine(configurations.Collect());

        context.RegisterSourceOutput(compilationAndConfigs,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(Compilation compilation, ImmutableArray<INamedTypeSymbol?> configs,
        SourceProductionContext context)
    {
        if (configs.IsDefaultOrEmpty)
        {
            return;
        }

        List<INamedTypeSymbol> distinctConfigs = configs
            .Where(c => c is not null)
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>()
            .OrderBy(c => c.Name)
            .ToList();

        string rootNamespace = compilation.AssemblyName ?? "Infrastructure";

        StringBuilder sb = new();

        sb.AppendLine($$"""
                      // <auto-generated />
                      using global::Microsoft.EntityFrameworkCore;

                      namespace {{rootNamespace}};

                      public static partial class ModelBuilderGeneratedExtensions
                      {
                          public static void ApplyGeneratedConfigurations(this ModelBuilder modelBuilder)
                          {
                      """);

        foreach (INamedTypeSymbol? config in distinctConfigs)
        {
            string fullName = config.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.AppendLine($"        modelBuilder.ApplyConfiguration(new {fullName}());");
        }

        sb.AppendLine("""
                          }
                      }
                      """);

        context.AddSource("ModelBuilderGeneratedExtensions.g.cs", sb.ToString());
    }
}
