<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../TestProjects.props" />
  <ItemGroup>
    <ProjectReference Include="../Consumer.Application/Consumer.Application.csproj" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.15.0" />
    <PackageReference Include="Testcontainers.Redis" Version="4.15.0" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <Compile Include="../../Shared/ValidatorTestBase.cs" Link="Shared/ValidatorTestBase.cs" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>
</Project>
