using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SebastianGuzmanMorla.DDD.Domain.Generator;

[Generator]
public sealed class ClearSensitivePropertiesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<ClassDeclarationSyntax> classDeclarations =
            context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (ctx, _) => (ClassDeclarationSyntax)ctx.Node
            );

        IncrementalValueProvider<ImmutableArray<ClassDeclarationSyntax>> candidates = classDeclarations.Collect();

        context.RegisterSourceOutput(context.CompilationProvider.Combine(candidates),
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes,
        SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty)
        {
            return;
        }

        INamedTypeSymbol? requestSymbol = compilation.GetTypeByMetadataName("SebastianGuzmanMorla.DDD.Domain.Messaging.Request");
        INamedTypeSymbol? sensitiveAttributeSymbol =
            compilation.GetTypeByMetadataName("SebastianGuzmanMorla.DDD.Domain.Attributes.SensitiveDataAttribute");

        if (requestSymbol is null || sensitiveAttributeSymbol is null)
        {
            return;
        }

        HashSet<ISymbol> generated = new(SymbolEqualityComparer.Default);
        foreach (ClassDeclarationSyntax classDeclaration in classes)
        {
            SemanticModel semanticModel = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(classDeclaration) is not { } classSymbol)
            {
                continue;
            }

            if (classSymbol.IsAbstract || !InheritsFrom(classSymbol, requestSymbol))
            {
                continue;
            }

            if (!generated.Add(classSymbol)) continue;

            // Only generate if it is partial
            if (!classDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            {
                continue;
            }

            // Only generate if it doesn't already have an implementation
            if (classSymbol.GetMembers("ClearSensitiveProperties").Any(m => m is IMethodSymbol
                {
                    IsOverride: true, IsImplicitlyDeclared: false
                }))
            {
                continue;
            }

            List<IPropertySymbol> sensitiveProperties = new();
            for (INamedTypeSymbol? current = classSymbol; current is not null; current = current.BaseType)
            {
                sensitiveProperties.AddRange(current.GetMembers().OfType<IPropertySymbol>()
                    .Where(p => p.GetAttributes().Any(a =>
                        SymbolEqualityComparer.Default.Equals(a.AttributeClass, sensitiveAttributeSymbol)))
                    .Where(p => SymbolEqualityComparer.Default.Equals(current, classSymbol) ||
                        (p.SetMethod is not null && compilation.IsSymbolAccessibleWithin(p, classSymbol) &&
                         compilation.IsSymbolAccessibleWithin(p.SetMethod, classSymbol))));
            }

            StringBuilder sb = new();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            if (!classSymbol.ContainingNamespace.IsGlobalNamespace)
                sb.AppendLine($"namespace {classSymbol.ContainingNamespace.ToDisplayString()};");
            sb.AppendLine();

            // Reopen each containing partial type, preserving accessibility and generic parameters.
            Stack<INamedTypeSymbol> containers = new();
            for (INamedTypeSymbol? current = classSymbol; current is not null; current = current.ContainingType)
                containers.Push(current);
            int typeCount = containers.Count;
            foreach (INamedTypeSymbol type in containers)
            {
                TypeDeclarationSyntax declaration = (TypeDeclarationSyntax)type.DeclaringSyntaxReferences[0].GetSyntax();
                string keyword = declaration is RecordDeclarationSyntax record
                    ? $"record {record.ClassOrStructKeyword.Text}"
                    : declaration.Keyword.Text;
                sb.AppendLine($"{declaration.Modifiers} {keyword} @{type.Name}{declaration.TypeParameterList}");
                sb.AppendLine("{");
            }
            sb.AppendLine("    public override void ClearSensitiveProperties()");
            sb.AppendLine("    {");

            // Preserve custom redaction in a base class, including its private state.
            for (INamedTypeSymbol? current = classSymbol.BaseType; current is not null; current = current.BaseType)
            {
                IMethodSymbol? method = current.GetMembers("ClearSensitiveProperties")
                    .OfType<IMethodSymbol>().FirstOrDefault(m => !m.IsStatic && m.Parameters.Length == 0);
                if (method is null && !current.IsAbstract && InheritsFrom(current, requestSymbol) &&
                    current.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is ClassDeclarationSyntax c &&
                        c.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword))))
                {
                    // The base implementation is emitted in this same generator run.
                    sb.AppendLine("        base.ClearSensitiveProperties();");
                    break;
                }
                if (method is null) continue;
                if (!method.IsAbstract) sb.AppendLine("        base.ClearSensitiveProperties();");
                break;
            }

            foreach (IPropertySymbol prop in sensitiveProperties)
            {
                string receiver = "this";
                if (prop.IsStatic)
                {
                    receiver = prop.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                }
                else if (!SymbolEqualityComparer.Default.Equals(prop.ContainingType, classSymbol))
                {
                    // A derived property may hide a public sensitive property with the same name.
                    receiver = prop.DeclaredAccessibility == Accessibility.Public &&
                               prop.SetMethod?.DeclaredAccessibility == Accessibility.Public
                        ? $"(({prop.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})this)"
                        : "base";
                }

                sb.AppendLine($"        {receiver}.@{prop.Name} = default;");
            }

            sb.AppendLine("    }");
            for (int i = 0; i < typeCount; i++) sb.AppendLine("}");

            string identity = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            using var hash = System.Security.Cryptography.SHA256.Create();
            string hint = System.BitConverter.ToString(hash.ComputeHash(Encoding.UTF8.GetBytes(identity))).Replace("-", "");
            context.AddSource($"{hint}.ClearSensitiveProperties.g.cs", sb.ToString());
        }
    }

    private static bool InheritsFrom(INamedTypeSymbol type, INamedTypeSymbol baseType)
    {
        INamedTypeSymbol? current = type.BaseType;

        while (current is not null)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseType))
            {
                return true;
            }

            if (SymbolEqualityComparer.Default.Equals(current.OriginalDefinition, baseType))
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }
}
