using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SebastianGuzmanMorla.DDD.Domain.Generator;

[Generator]
public sealed class ClearSensitivePropertiesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<ClassDeclarationSyntax> classDeclarations =
            context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (ctx, _) => (ClassDeclarationSyntax)ctx.Node
            );

        IncrementalValueProvider<ImmutableArray<ClassDeclarationSyntax>> candidates = classDeclarations.Collect();

        context.RegisterSourceOutput(context.CompilationProvider.Combine(candidates),
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes,
        SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty)
        {
            return;
        }

        INamedTypeSymbol? requestSymbol = compilation.GetTypeByMetadataName("SebastianGuzmanMorla.DDD.Domain.Messaging.Request");
        INamedTypeSymbol? sensitiveAttributeSymbol =
            compilation.GetTypeByMetadataName("SebastianGuzmanMorla.DDD.Domain.Attributes.SensitiveDataAttribute");

        if (requestSymbol is null || sensitiveAttributeSymbol is null)
        {
            return;
        }

        foreach (ClassDeclarationSyntax classDeclaration in classes)
        {
            SemanticModel semanticModel = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(classDeclaration) is not { } classSymbol)
            {
                continue;
            }

            if (classSymbol.IsAbstract || !InheritsFrom(classSymbol, requestSymbol))
            {
                continue;
            }

            // Only generate if it is partial
            if (!classDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            {
                continue;
            }

            // Only generate if it doesn't already have an implementation
            if (classSymbol.GetMembers("ClearSensitiveProperties").Any(m => m is IMethodSymbol
                {
                    IsOverride: true, IsImplicitlyDeclared: false
                }))
            {
                continue;
            }

            List<IPropertySymbol> sensitiveProperties = classSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.GetAttributes().Any(a =>
                    SymbolEqualityComparer.Default.Equals(a.AttributeClass, sensitiveAttributeSymbol)))
                .ToList();

            string ns = classSymbol.ContainingNamespace.ToDisplayString();
            string className = classSymbol.Name;

            StringBuilder sb = new();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
            sb.AppendLine($"public partial class {className}");
            sb.AppendLine("{");
            sb.AppendLine("    public override void ClearSensitiveProperties()");
            sb.AppendLine("    {");

            foreach (IPropertySymbol? prop in sensitiveProperties) sb.AppendLine($"        {prop.Name} = default;");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource($"{className}.ClearSensitiveProperties.g.cs", sb.ToString());
        }
    }

    private static bool InheritsFrom(INamedTypeSymbol type, INamedTypeSymbol baseType)
    {
        INamedTypeSymbol? current = type.BaseType;

        while (current is not null)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseType))
            {
                return true;
            }

            if (SymbolEqualityComparer.Default.Equals(current.OriginalDefinition, baseType))
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }
}
